/**
 *
 * Character classes
 *
 * By John Snelson
 *
 */

#include <faxpp/char_classes.h>

typedef struct CharClass_s {

  Char32 c;
  uint8_t flags;

} CharClass;

/*
 * [2]     Char     ::=    [#x1-#xD7FF] | [#xE000-#xFFFD] | [#x10000-#x10FFFF]
 * [2a]    RestrictedChar     ::=    [#x1-#x8] | [#xB-#xC] | [#xE-#x1F] |
 *                                   [#x7F-#x84] | [#x86-#x9F]
 *
 * [3]     S    ::=    (#x20 | #x9 | #xD | #xA)+
 *
 * [4]     NameStartChar    ::=    ":" | [A-Z] | "_" | [a-z] | [#xC0-#xD6] |
 *                                 [#xD8-#xF6] | [#xF8-#x2FF] | [#x370-#x37D] |
 *                                 [#x37F-#x1FFF] | [#x200C-#x200D] |
 *                                 [#x2070-#x218F] | [#x2C00-#x2FEF] |
 *                                 [#x3001-#xD7FF] | [#xF900-#xFDCF] |
 *                                 [#xFDF0-#xFFFD] | [#x10000-#xEFFFF]
 * [4a]    NameChar     ::=    NameStartChar | "-" | "." | [0-9] | #xB7 |
 *                             [#x0300-#x036F] | [#x203F-#x2040]
 *
 * [5]     NCNameChar     ::=    NameChar - ':'
 * [5a]    NCNameStartChar    ::=    NameStartChar - ':'
 *
 * '-' = 0x2D, '.' = 0x2E, '0' = 0x30, '9' = 0x39, ':' = 0x3A, 'A' = 0x41, 'Z' = 0x5A, '_' = 0x5F, 'a' = 0x61, 'z' = 0x7A
 */

#define CHAR_CLASSES_SIZE 24
static const CharClass char_classes[CHAR_CLASSES_SIZE] = {
  // Don't need the region between 0x00 and 0xFF, since we look
  // them up directly in the table below

/*   { 0x000000, 0 }, */
/*   { 0x000009, NON_RESTRICTED_CHAR | WHITESPACE_CHAR }, */
/*   { 0x00000B, 0 }, */
/*   { 0x00000D, NON_RESTRICTED_CHAR | WHITESPACE_CHAR }, */
/*   { 0x00000E, 0 }, */
/*   { 0x000020, NON_RESTRICTED_CHAR | WHITESPACE_CHAR }, */
/*   { 0x000021, NON_RESTRICTED_CHAR }, */
/*   { 0x00002D, NON_RESTRICTED_CHAR | NAME_CHAR | NCNAME_CHAR }, */
/*   { 0x00002F, NON_RESTRICTED_CHAR }, */
/*   { 0x000030, NON_RESTRICTED_CHAR | NAME_CHAR | NCNAME_CHAR }, */
/*   { 0x00003A, NON_RESTRICTED_CHAR | NAME_START_CHAR | NAME_CHAR }, */
/*   { 0x00003B, NON_RESTRICTED_CHAR }, */
/*   { 0x000041, NON_RESTRICTED_CHAR | NAME_START_CHAR | NCNAME_START_CHAR | NAME_CHAR | NCNAME_CHAR }, */
/*   { 0x00005B, NON_RESTRICTED_CHAR }, */
/*   { 0x00005F, NON_RESTRICTED_CHAR | NAME_START_CHAR | NCNAME_START_CHAR | NAME_CHAR | NCNAME_CHAR }, */
/*   { 0x000060, NON_RESTRICTED_CHAR }, */
/*   { 0x000061, NON_RESTRICTED_CHAR | NAME_START_CHAR | NCNAME_START_CHAR | NAME_CHAR | NCNAME_CHAR }, */
/*   { 0x00007B, NON_RESTRICTED_CHAR }, */
/*   { 0x00007F, 0 }, */
/*   { 0x000085, NON_RESTRICTED_CHAR }, */
/*   { 0x000086, 0 }, */
/*   { 0x0000A0, NON_RESTRICTED_CHAR }, */
/*   { 0x0000B7, NON_RESTRICTED_CHAR | NAME_CHAR | NCNAME_CHAR }, */
/*   { 0x0000B8, NON_RESTRICTED_CHAR }, */
/*   { 0x0000C0, NON_RESTRICTED_CHAR | NAME_START_CHAR | NCNAME_START_CHAR | NAME_CHAR | NCNAME_CHAR }, */
/*   { 0x0000D7, NON_RESTRICTED_CHAR }, */
/*   { 0x0000D8, NON_RESTRICTED_CHAR | NAME_START_CHAR | NCNAME_START_CHAR | NAME_CHAR | NCNAME_CHAR }, */
/*   { 0x0000F7, NON_RESTRICTED_CHAR }, */
  { 0x0000F8, NON_RESTRICTED_CHAR | NAME_START_CHAR | NCNAME_START_CHAR | NAME_CHAR | NCNAME_CHAR },

  { 0x000300, NON_RESTRICTED_CHAR | NAME_CHAR | NCNAME_CHAR },
  { 0x000370, NON_RESTRICTED_CHAR | NAME_START_CHAR | NCNAME_START_CHAR | NAME_CHAR | NCNAME_CHAR },
  { 0x00037E, NON_RESTRICTED_CHAR },
  { 0x00037F, NON_RESTRICTED_CHAR | NAME_START_CHAR | NCNAME_START_CHAR | NAME_CHAR | NCNAME_CHAR },
  { 0x002000, NON_RESTRICTED_CHAR },
  { 0x00200C, NON_RESTRICTED_CHAR | NAME_START_CHAR | NCNAME_START_CHAR | NAME_CHAR | NCNAME_CHAR },
  { 0x00200E, NON_RESTRICTED_CHAR },
  { 0x00203F, NON_RESTRICTED_CHAR | NAME_CHAR | NCNAME_CHAR },
  { 0x002041, NON_RESTRICTED_CHAR },
  { 0x002070, NON_RESTRICTED_CHAR | NAME_START_CHAR | NCNAME_START_CHAR | NAME_CHAR | NCNAME_CHAR },
  { 0x002190, NON_RESTRICTED_CHAR },
  { 0x002C00, NON_RESTRICTED_CHAR | NAME_START_CHAR | NCNAME_START_CHAR | NAME_CHAR | NCNAME_CHAR },
  { 0x002FF0, NON_RESTRICTED_CHAR },
  { 0x003001, NON_RESTRICTED_CHAR | NAME_START_CHAR | NCNAME_START_CHAR | NAME_CHAR | NCNAME_CHAR },
  { 0x00D800, 0 },
  { 0x00E000, NON_RESTRICTED_CHAR },
  { 0x00F900, NON_RESTRICTED_CHAR | NAME_START_CHAR | NCNAME_START_CHAR | NAME_CHAR | NCNAME_CHAR },
  { 0x00FDD0, NON_RESTRICTED_CHAR },
  { 0x00FDF0, NON_RESTRICTED_CHAR | NAME_START_CHAR | NCNAME_START_CHAR | NAME_CHAR | NCNAME_CHAR },
  { 0x00FFFE, 0 },
  { 0x010000, NON_RESTRICTED_CHAR | NAME_START_CHAR | NCNAME_START_CHAR | NAME_CHAR | NCNAME_CHAR },
  { 0x0F0000, NON_RESTRICTED_CHAR },
  { 0x110000, 0 }
};

const uint8_t char_flags_256[256] = {
  /* 0x00 */ 0,
  /* 0x01 */ 0,
  /* 0x02 */ 0,
  /* 0x03 */ 0,
  /* 0x04 */ 0,
  /* 0x05 */ 0,
  /* 0x06 */ 0,
  /* 0x07 */ 0,
  /* 0x08 */ 0,
  /* 0x09 */ NON_RESTRICTED_CHAR | WHITESPACE_CHAR,
  /* 0x0A */ NON_RESTRICTED_CHAR | WHITESPACE_CHAR,
  /* 0x0B */ 0,
  /* 0x0C */ 0,
  /* 0x0D */ NON_RESTRICTED_CHAR | WHITESPACE_CHAR,
  /* 0x0E */ 0,
  /* 0x0F */ 0,
  /* 0x10 */ 0,
  /* 0x11 */ 0,
  /* 0x12 */ 0,
  /* 0x13 */ 0,
  /* 0x14 */ 0,
  /* 0x15 */ 0,
  /* 0x16 */ 0,
  /* 0x17 */ 0,
  /* 0x18 */ 0,
  /* 0x19 */ 0,
  /* 0x1A */ 0,
  /* 0x1B */ 0,
  /* 0x1C */ 0,
  /* 0x1D */ 0,
  /* 0x1E */ 0,
  /* 0x1F */ 0,
  /* 0x20 */ NON_RESTRICTED_CHAR | WHITESPACE_CHAR,
  /* 0x21 */ NON_RESTRICTED_CHAR,
  /* 0x22 */ NON_RESTRICTED_CHAR,
  /* 0x23 */ NON_RESTRICTED_CHAR,
  /* 0x24 */ NON_RESTRICTED_CHAR,
  /* 0x25 */ NON_RESTRICTED_CHAR,
  /* 0x26 */ NON_RESTRICTED_CHAR,
  /* 0x27 */ NON_RESTRICTED_CHAR,
  /* 0x28 */ NON_RESTRICTED_CHAR,
  /* 0x29 */ NON_RESTRICTED_CHAR,
  /* 0x2A */ NON_RESTRICTED_CHAR,
  /* 0x2B */ NON_RESTRICTED_CHAR,
  /* 0x2C */ NON_RESTRICTED_CHAR,
  /* 0x2D */ NON_RESTRICTED_CHAR | NAME_CHAR | NCNAME_CHAR,
  /* 0x2E */ NON_RESTRICTED_CHAR | NAME_CHAR | NCNAME_CHAR,
  /* 0x2F */ NON_RESTRICTED_CHAR,
  /* 0x30 */ NON_RESTRICTED_CHAR | NAME_CHAR | NCNAME_CHAR,
  /* 0x31 */ NON_RESTRICTED_CHAR | NAME_CHAR | NCNAME_CHAR,
  /* 0x32 */ NON_RESTRICTED_CHAR | NAME_CHAR | NCNAME_CHAR,
  /* 0x33 */ NON_RESTRICTED_CHAR | NAME_CHAR | NCNAME_CHAR,
  /* 0x34 */ NON_RESTRICTED_CHAR | NAME_CHAR | NCNAME_CHAR,
  /* 0x35 */ NON_RESTRICTED_CHAR | NAME_CHAR | NCNAME_CHAR,
  /* 0x36 */ NON_RESTRICTED_CHAR | NAME_CHAR | NCNAME_CHAR,
  /* 0x37 */ NON_RESTRICTED_CHAR | NAME_CHAR | NCNAME_CHAR,
  /* 0x38 */ NON_RESTRICTED_CHAR | NAME_CHAR | NCNAME_CHAR,
  /* 0x39 */ NON_RESTRICTED_CHAR | NAME_CHAR | NCNAME_CHAR,
  /* 0x3A */ NON_RESTRICTED_CHAR | NAME_START_CHAR | NAME_CHAR,
  /* 0x3B */ NON_RESTRICTED_CHAR,
  /* 0x3C */ NON_RESTRICTED_CHAR,
  /* 0x3D */ NON_RESTRICTED_CHAR,
  /* 0x3E */ NON_RESTRICTED_CHAR,
  /* 0x3F */ NON_RESTRICTED_CHAR,
  /* 0x40 */ NON_RESTRICTED_CHAR,
  /* 0x41 */ NON_RESTRICTED_CHAR | NAME_START_CHAR | NCNAME_START_CHAR | NAME_CHAR | NCNAME_CHAR,
  /* 0x42 */ NON_RESTRICTED_CHAR | NAME_START_CHAR | NCNAME_START_CHAR | NAME_CHAR | NCNAME_CHAR,
  /* 0x43 */ NON_RESTRICTED_CHAR | NAME_START_CHAR | NCNAME_START_CHAR | NAME_CHAR | NCNAME_CHAR,
  /* 0x44 */ NON_RESTRICTED_CHAR | NAME_START_CHAR | NCNAME_START_CHAR | NAME_CHAR | NCNAME_CHAR,
  /* 0x45 */ NON_RESTRICTED_CHAR | NAME_START_CHAR | NCNAME_START_CHAR | NAME_CHAR | NCNAME_CHAR,
  /* 0x46 */ NON_RESTRICTED_CHAR | NAME_START_CHAR | NCNAME_START_CHAR | NAME_CHAR | NCNAME_CHAR,
  /* 0x47 */ NON_RESTRICTED_CHAR | NAME_START_CHAR | NCNAME_START_CHAR | NAME_CHAR | NCNAME_CHAR,
  /* 0x48 */ NON_RESTRICTED_CHAR | NAME_START_CHAR | NCNAME_START_CHAR | NAME_CHAR | NCNAME_CHAR,
  /* 0x49 */ NON_RESTRICTED_CHAR | NAME_START_CHAR | NCNAME_START_CHAR | NAME_CHAR | NCNAME_CHAR,
  /* 0x4A */ NON_RESTRICTED_CHAR | NAME_START_CHAR | NCNAME_START_CHAR | NAME_CHAR | NCNAME_CHAR,
  /* 0x4B */ NON_RESTRICTED_CHAR | NAME_START_CHAR | NCNAME_START_CHAR | NAME_CHAR | NCNAME_CHAR,
  /* 0x4C */ NON_RESTRICTED_CHAR | NAME_START_CHAR | NCNAME_START_CHAR | NAME_CHAR | NCNAME_CHAR,
  /* 0x4D */ NON_RESTRICTED_CHAR | NAME_START_CHAR | NCNAME_START_CHAR | NAME_CHAR | NCNAME_CHAR,
  /* 0x4E */ NON_RESTRICTED_CHAR | NAME_START_CHAR | NCNAME_START_CHAR | NAME_CHAR | NCNAME_CHAR,
  /* 0x4F */ NON_RESTRICTED_CHAR | NAME_START_CHAR | NCNAME_START_CHAR | NAME_CHAR | NCNAME_CHAR,
  /* 0x50 */ NON_RESTRICTED_CHAR | NAME_START_CHAR | NCNAME_START_CHAR | NAME_CHAR | NCNAME_CHAR,
  /* 0x51 */ NON_RESTRICTED_CHAR | NAME_START_CHAR | NCNAME_START_CHAR | NAME_CHAR | NCNAME_CHAR,
  /* 0x52 */ NON_RESTRICTED_CHAR | NAME_START_CHAR | NCNAME_START_CHAR | NAME_CHAR | NCNAME_CHAR,
  /* 0x53 */ NON_RESTRICTED_CHAR | NAME_START_CHAR | NCNAME_START_CHAR | NAME_CHAR | NCNAME_CHAR,
  /* 0x54 */ NON_RESTRICTED_CHAR | NAME_START_CHAR | NCNAME_START_CHAR | NAME_CHAR | NCNAME_CHAR,
  /* 0x55 */ NON_RESTRICTED_CHAR | NAME_START_CHAR | NCNAME_START_CHAR | NAME_CHAR | NCNAME_CHAR,
  /* 0x56 */ NON_RESTRICTED_CHAR | NAME_START_CHAR | NCNAME_START_CHAR | NAME_CHAR | NCNAME_CHAR,
  /* 0x57 */ NON_RESTRICTED_CHAR | NAME_START_CHAR | NCNAME_START_CHAR | NAME_CHAR | NCNAME_CHAR,
  /* 0x58 */ NON_RESTRICTED_CHAR | NAME_START_CHAR | NCNAME_START_CHAR | NAME_CHAR | NCNAME_CHAR,
  /* 0x59 */ NON_RESTRICTED_CHAR | NAME_START_CHAR | NCNAME_START_CHAR | NAME_CHAR | NCNAME_CHAR,
  /* 0x5A */ NON_RESTRICTED_CHAR | NAME_START_CHAR | NCNAME_START_CHAR | NAME_CHAR | NCNAME_CHAR,
  /* 0x5B */ NON_RESTRICTED_CHAR,
  /* 0x5C */ NON_RESTRICTED_CHAR,
  /* 0x5D */ NON_RESTRICTED_CHAR,
  /* 0x5E */ NON_RESTRICTED_CHAR,
  /* 0x5F */ NON_RESTRICTED_CHAR | NAME_START_CHAR | NCNAME_START_CHAR | NAME_CHAR | NCNAME_CHAR,
  /* 0x60 */ NON_RESTRICTED_CHAR,
  /* 0x61 */ NON_RESTRICTED_CHAR | NAME_START_CHAR | NCNAME_START_CHAR | NAME_CHAR | NCNAME_CHAR,
  /* 0x62 */ NON_RESTRICTED_CHAR | NAME_START_CHAR | NCNAME_START_CHAR | NAME_CHAR | NCNAME_CHAR,
  /* 0x63 */ NON_RESTRICTED_CHAR | NAME_START_CHAR | NCNAME_START_CHAR | NAME_CHAR | NCNAME_CHAR,
  /* 0x64 */ NON_RESTRICTED_CHAR | NAME_START_CHAR | NCNAME_START_CHAR | NAME_CHAR | NCNAME_CHAR,
  /* 0x65 */ NON_RESTRICTED_CHAR | NAME_START_CHAR | NCNAME_START_CHAR | NAME_CHAR | NCNAME_CHAR,
  /* 0x66 */ NON_RESTRICTED_CHAR | NAME_START_CHAR | NCNAME_START_CHAR | NAME_CHAR | NCNAME_CHAR,
  /* 0x67 */ NON_RESTRICTED_CHAR | NAME_START_CHAR | NCNAME_START_CHAR | NAME_CHAR | NCNAME_CHAR,
  /* 0x68 */ NON_RESTRICTED_CHAR | NAME_START_CHAR | NCNAME_START_CHAR | NAME_CHAR | NCNAME_CHAR,
  /* 0x69 */ NON_RESTRICTED_CHAR | NAME_START_CHAR | NCNAME_START_CHAR | NAME_CHAR | NCNAME_CHAR,
  /* 0x6A */ NON_RESTRICTED_CHAR | NAME_START_CHAR | NCNAME_START_CHAR | NAME_CHAR | NCNAME_CHAR,
  /* 0x6B */ NON_RESTRICTED_CHAR | NAME_START_CHAR | NCNAME_START_CHAR | NAME_CHAR | NCNAME_CHAR,
  /* 0x6C */ NON_RESTRICTED_CHAR | NAME_START_CHAR | NCNAME_START_CHAR | NAME_CHAR | NCNAME_CHAR,
  /* 0x6D */ NON_RESTRICTED_CHAR | NAME_START_CHAR | NCNAME_START_CHAR | NAME_CHAR | NCNAME_CHAR,
  /* 0x6E */ NON_RESTRICTED_CHAR | NAME_START_CHAR | NCNAME_START_CHAR | NAME_CHAR | NCNAME_CHAR,
  /* 0x6F */ NON_RESTRICTED_CHAR | NAME_START_CHAR | NCNAME_START_CHAR | NAME_CHAR | NCNAME_CHAR,
  /* 0x70 */ NON_RESTRICTED_CHAR | NAME_START_CHAR | NCNAME_START_CHAR | NAME_CHAR | NCNAME_CHAR,
  /* 0x71 */ NON_RESTRICTED_CHAR | NAME_START_CHAR | NCNAME_START_CHAR | NAME_CHAR | NCNAME_CHAR,
  /* 0x72 */ NON_RESTRICTED_CHAR | NAME_START_CHAR | NCNAME_START_CHAR | NAME_CHAR | NCNAME_CHAR,
  /* 0x73 */ NON_RESTRICTED_CHAR | NAME_START_CHAR | NCNAME_START_CHAR | NAME_CHAR | NCNAME_CHAR,
  /* 0x74 */ NON_RESTRICTED_CHAR | NAME_START_CHAR | NCNAME_START_CHAR | NAME_CHAR | NCNAME_CHAR,
  /* 0x75 */ NON_RESTRICTED_CHAR | NAME_START_CHAR | NCNAME_START_CHAR | NAME_CHAR | NCNAME_CHAR,
  /* 0x76 */ NON_RESTRICTED_CHAR | NAME_START_CHAR | NCNAME_START_CHAR | NAME_CHAR | NCNAME_CHAR,
  /* 0x77 */ NON_RESTRICTED_CHAR | NAME_START_CHAR | NCNAME_START_CHAR | NAME_CHAR | NCNAME_CHAR,
  /* 0x78 */ NON_RESTRICTED_CHAR | NAME_START_CHAR | NCNAME_START_CHAR | NAME_CHAR | NCNAME_CHAR,
  /* 0x79 */ NON_RESTRICTED_CHAR | NAME_START_CHAR | NCNAME_START_CHAR | NAME_CHAR | NCNAME_CHAR,
  /* 0x7A */ NON_RESTRICTED_CHAR | NAME_START_CHAR | NCNAME_START_CHAR | NAME_CHAR | NCNAME_CHAR,
  /* 0x7B */ NON_RESTRICTED_CHAR,
  /* 0x7C */ NON_RESTRICTED_CHAR,
  /* 0x7D */ NON_RESTRICTED_CHAR,
  /* 0x7E */ NON_RESTRICTED_CHAR,
  /* 0x7F */ 0,
  /* 0x80 */ 0,
  /* 0x81 */ 0,
  /* 0x82 */ 0,
  /* 0x83 */ 0,
  /* 0x84 */ 0,
  /* 0x85 */ NON_RESTRICTED_CHAR,
  /* 0x86 */ 0,
  /* 0x87 */ 0,
  /* 0x88 */ 0,
  /* 0x89 */ 0,
  /* 0x8A */ 0,
  /* 0x8B */ 0,
  /* 0x8C */ 0,
  /* 0x8D */ 0,
  /* 0x8E */ 0,
  /* 0x8F */ 0,
  /* 0x90 */ 0,
  /* 0x91 */ 0,
  /* 0x92 */ 0,
  /* 0x93 */ 0,
  /* 0x94 */ 0,
  /* 0x95 */ 0,
  /* 0x96 */ 0,
  /* 0x97 */ 0,
  /* 0x98 */ 0,
  /* 0x99 */ 0,
  /* 0x9A */ 0,
  /* 0x9B */ 0,
  /* 0x9C */ 0,
  /* 0x9D */ 0,
  /* 0x9E */ 0,
  /* 0x9F */ 0,
  /* 0xA0 */ NON_RESTRICTED_CHAR,
  /* 0xA1 */ NON_RESTRICTED_CHAR,
  /* 0xA2 */ NON_RESTRICTED_CHAR,
  /* 0xA3 */ NON_RESTRICTED_CHAR,
  /* 0xA4 */ NON_RESTRICTED_CHAR,
  /* 0xA5 */ NON_RESTRICTED_CHAR,
  /* 0xA6 */ NON_RESTRICTED_CHAR,
  /* 0xA7 */ NON_RESTRICTED_CHAR,
  /* 0xA8 */ NON_RESTRICTED_CHAR,
  /* 0xA9 */ NON_RESTRICTED_CHAR,
  /* 0xAA */ NON_RESTRICTED_CHAR,
  /* 0xAB */ NON_RESTRICTED_CHAR,
  /* 0xAC */ NON_RESTRICTED_CHAR,
  /* 0xAD */ NON_RESTRICTED_CHAR,
  /* 0xAE */ NON_RESTRICTED_CHAR,
  /* 0xAF */ NON_RESTRICTED_CHAR,
  /* 0xB0 */ NON_RESTRICTED_CHAR,
  /* 0xB1 */ NON_RESTRICTED_CHAR,
  /* 0xB2 */ NON_RESTRICTED_CHAR,
  /* 0xB3 */ NON_RESTRICTED_CHAR,
  /* 0xB4 */ NON_RESTRICTED_CHAR,
  /* 0xB5 */ NON_RESTRICTED_CHAR,
  /* 0xB6 */ NON_RESTRICTED_CHAR,
  /* 0xB7 */ NON_RESTRICTED_CHAR | NAME_CHAR | NCNAME_CHAR,
  /* 0xB8 */ NON_RESTRICTED_CHAR,
  /* 0xB9 */ NON_RESTRICTED_CHAR,
  /* 0xBA */ NON_RESTRICTED_CHAR,
  /* 0xBB */ NON_RESTRICTED_CHAR,
  /* 0xBC */ NON_RESTRICTED_CHAR,
  /* 0xBD */ NON_RESTRICTED_CHAR,
  /* 0xBE */ NON_RESTRICTED_CHAR,
  /* 0xBF */ NON_RESTRICTED_CHAR,
  /* 0xC0 */ NON_RESTRICTED_CHAR | NAME_START_CHAR | NCNAME_START_CHAR | NAME_CHAR | NCNAME_CHAR,
  /* 0xC1 */ NON_RESTRICTED_CHAR | NAME_START_CHAR | NCNAME_START_CHAR | NAME_CHAR | NCNAME_CHAR,
  /* 0xC2 */ NON_RESTRICTED_CHAR | NAME_START_CHAR | NCNAME_START_CHAR | NAME_CHAR | NCNAME_CHAR,
  /* 0xC3 */ NON_RESTRICTED_CHAR | NAME_START_CHAR | NCNAME_START_CHAR | NAME_CHAR | NCNAME_CHAR,
  /* 0xC4 */ NON_RESTRICTED_CHAR | NAME_START_CHAR | NCNAME_START_CHAR | NAME_CHAR | NCNAME_CHAR,
  /* 0xC5 */ NON_RESTRICTED_CHAR | NAME_START_CHAR | NCNAME_START_CHAR | NAME_CHAR | NCNAME_CHAR,
  /* 0xC6 */ NON_RESTRICTED_CHAR | NAME_START_CHAR | NCNAME_START_CHAR | NAME_CHAR | NCNAME_CHAR,
  /* 0xC7 */ NON_RESTRICTED_CHAR | NAME_START_CHAR | NCNAME_START_CHAR | NAME_CHAR | NCNAME_CHAR,
  /* 0xC8 */ NON_RESTRICTED_CHAR | NAME_START_CHAR | NCNAME_START_CHAR | NAME_CHAR | NCNAME_CHAR,
  /* 0xC9 */ NON_RESTRICTED_CHAR | NAME_START_CHAR | NCNAME_START_CHAR | NAME_CHAR | NCNAME_CHAR,
  /* 0xCA */ NON_RESTRICTED_CHAR | NAME_START_CHAR | NCNAME_START_CHAR | NAME_CHAR | NCNAME_CHAR,
  /* 0xCB */ NON_RESTRICTED_CHAR | NAME_START_CHAR | NCNAME_START_CHAR | NAME_CHAR | NCNAME_CHAR,
  /* 0xCC */ NON_RESTRICTED_CHAR | NAME_START_CHAR | NCNAME_START_CHAR | NAME_CHAR | NCNAME_CHAR,
  /* 0xCD */ NON_RESTRICTED_CHAR | NAME_START_CHAR | NCNAME_START_CHAR | NAME_CHAR | NCNAME_CHAR,
  /* 0xCE */ NON_RESTRICTED_CHAR | NAME_START_CHAR | NCNAME_START_CHAR | NAME_CHAR | NCNAME_CHAR,
  /* 0xCF */ NON_RESTRICTED_CHAR | NAME_START_CHAR | NCNAME_START_CHAR | NAME_CHAR | NCNAME_CHAR,
  /* 0xD0 */ NON_RESTRICTED_CHAR | NAME_START_CHAR | NCNAME_START_CHAR | NAME_CHAR | NCNAME_CHAR,
  /* 0xD1 */ NON_RESTRICTED_CHAR | NAME_START_CHAR | NCNAME_START_CHAR | NAME_CHAR | NCNAME_CHAR,
  /* 0xD2 */ NON_RESTRICTED_CHAR | NAME_START_CHAR | NCNAME_START_CHAR | NAME_CHAR | NCNAME_CHAR,
  /* 0xD3 */ NON_RESTRICTED_CHAR | NAME_START_CHAR | NCNAME_START_CHAR | NAME_CHAR | NCNAME_CHAR,
  /* 0xD4 */ NON_RESTRICTED_CHAR | NAME_START_CHAR | NCNAME_START_CHAR | NAME_CHAR | NCNAME_CHAR,
  /* 0xD5 */ NON_RESTRICTED_CHAR | NAME_START_CHAR | NCNAME_START_CHAR | NAME_CHAR | NCNAME_CHAR,
  /* 0xD6 */ NON_RESTRICTED_CHAR | NAME_START_CHAR | NCNAME_START_CHAR | NAME_CHAR | NCNAME_CHAR,
  /* 0xD7 */ NON_RESTRICTED_CHAR,
  /* 0xD8 */ NON_RESTRICTED_CHAR | NAME_START_CHAR | NCNAME_START_CHAR | NAME_CHAR | NCNAME_CHAR,
  /* 0xD9 */ NON_RESTRICTED_CHAR | NAME_START_CHAR | NCNAME_START_CHAR | NAME_CHAR | NCNAME_CHAR,
  /* 0xDA */ NON_RESTRICTED_CHAR | NAME_START_CHAR | NCNAME_START_CHAR | NAME_CHAR | NCNAME_CHAR,
  /* 0xDB */ NON_RESTRICTED_CHAR | NAME_START_CHAR | NCNAME_START_CHAR | NAME_CHAR | NCNAME_CHAR,
  /* 0xDC */ NON_RESTRICTED_CHAR | NAME_START_CHAR | NCNAME_START_CHAR | NAME_CHAR | NCNAME_CHAR,
  /* 0xDD */ NON_RESTRICTED_CHAR | NAME_START_CHAR | NCNAME_START_CHAR | NAME_CHAR | NCNAME_CHAR,
  /* 0xDE */ NON_RESTRICTED_CHAR | NAME_START_CHAR | NCNAME_START_CHAR | NAME_CHAR | NCNAME_CHAR,
  /* 0xDF */ NON_RESTRICTED_CHAR | NAME_START_CHAR | NCNAME_START_CHAR | NAME_CHAR | NCNAME_CHAR,
  /* 0xE0 */ NON_RESTRICTED_CHAR | NAME_START_CHAR | NCNAME_START_CHAR | NAME_CHAR | NCNAME_CHAR,
  /* 0xE1 */ NON_RESTRICTED_CHAR | NAME_START_CHAR | NCNAME_START_CHAR | NAME_CHAR | NCNAME_CHAR,
  /* 0xE2 */ NON_RESTRICTED_CHAR | NAME_START_CHAR | NCNAME_START_CHAR | NAME_CHAR | NCNAME_CHAR,
  /* 0xE3 */ NON_RESTRICTED_CHAR | NAME_START_CHAR | NCNAME_START_CHAR | NAME_CHAR | NCNAME_CHAR,
  /* 0xE4 */ NON_RESTRICTED_CHAR | NAME_START_CHAR | NCNAME_START_CHAR | NAME_CHAR | NCNAME_CHAR,
  /* 0xE5 */ NON_RESTRICTED_CHAR | NAME_START_CHAR | NCNAME_START_CHAR | NAME_CHAR | NCNAME_CHAR,
  /* 0xE6 */ NON_RESTRICTED_CHAR | NAME_START_CHAR | NCNAME_START_CHAR | NAME_CHAR | NCNAME_CHAR,
  /* 0xE7 */ NON_RESTRICTED_CHAR | NAME_START_CHAR | NCNAME_START_CHAR | NAME_CHAR | NCNAME_CHAR,
  /* 0xE8 */ NON_RESTRICTED_CHAR | NAME_START_CHAR | NCNAME_START_CHAR | NAME_CHAR | NCNAME_CHAR,
  /* 0xE9 */ NON_RESTRICTED_CHAR | NAME_START_CHAR | NCNAME_START_CHAR | NAME_CHAR | NCNAME_CHAR,
  /* 0xEA */ NON_RESTRICTED_CHAR | NAME_START_CHAR | NCNAME_START_CHAR | NAME_CHAR | NCNAME_CHAR,
  /* 0xEB */ NON_RESTRICTED_CHAR | NAME_START_CHAR | NCNAME_START_CHAR | NAME_CHAR | NCNAME_CHAR,
  /* 0xEC */ NON_RESTRICTED_CHAR | NAME_START_CHAR | NCNAME_START_CHAR | NAME_CHAR | NCNAME_CHAR,
  /* 0xED */ NON_RESTRICTED_CHAR | NAME_START_CHAR | NCNAME_START_CHAR | NAME_CHAR | NCNAME_CHAR,
  /* 0xEE */ NON_RESTRICTED_CHAR | NAME_START_CHAR | NCNAME_START_CHAR | NAME_CHAR | NCNAME_CHAR,
  /* 0xEF */ NON_RESTRICTED_CHAR | NAME_START_CHAR | NCNAME_START_CHAR | NAME_CHAR | NCNAME_CHAR,
  /* 0xF0 */ NON_RESTRICTED_CHAR | NAME_START_CHAR | NCNAME_START_CHAR | NAME_CHAR | NCNAME_CHAR,
  /* 0xF1 */ NON_RESTRICTED_CHAR | NAME_START_CHAR | NCNAME_START_CHAR | NAME_CHAR | NCNAME_CHAR,
  /* 0xF2 */ NON_RESTRICTED_CHAR | NAME_START_CHAR | NCNAME_START_CHAR | NAME_CHAR | NCNAME_CHAR,
  /* 0xF3 */ NON_RESTRICTED_CHAR | NAME_START_CHAR | NCNAME_START_CHAR | NAME_CHAR | NCNAME_CHAR,
  /* 0xF4 */ NON_RESTRICTED_CHAR | NAME_START_CHAR | NCNAME_START_CHAR | NAME_CHAR | NCNAME_CHAR,
  /* 0xF5 */ NON_RESTRICTED_CHAR | NAME_START_CHAR | NCNAME_START_CHAR | NAME_CHAR | NCNAME_CHAR,
  /* 0xF6 */ NON_RESTRICTED_CHAR | NAME_START_CHAR | NCNAME_START_CHAR | NAME_CHAR | NCNAME_CHAR,
  /* 0xF7 */ NON_RESTRICTED_CHAR,
  /* 0xF8 */ NON_RESTRICTED_CHAR | NAME_START_CHAR | NCNAME_START_CHAR | NAME_CHAR | NCNAME_CHAR,
  /* 0xF9 */ NON_RESTRICTED_CHAR | NAME_START_CHAR | NCNAME_START_CHAR | NAME_CHAR | NCNAME_CHAR,
  /* 0xFA */ NON_RESTRICTED_CHAR | NAME_START_CHAR | NCNAME_START_CHAR | NAME_CHAR | NCNAME_CHAR,
  /* 0xFB */ NON_RESTRICTED_CHAR | NAME_START_CHAR | NCNAME_START_CHAR | NAME_CHAR | NCNAME_CHAR,
  /* 0xFC */ NON_RESTRICTED_CHAR | NAME_START_CHAR | NCNAME_START_CHAR | NAME_CHAR | NCNAME_CHAR,
  /* 0xFD */ NON_RESTRICTED_CHAR | NAME_START_CHAR | NCNAME_START_CHAR | NAME_CHAR | NCNAME_CHAR,
  /* 0xFE */ NON_RESTRICTED_CHAR | NAME_START_CHAR | NCNAME_START_CHAR | NAME_CHAR | NCNAME_CHAR,
  /* 0xFF */ NON_RESTRICTED_CHAR | NAME_START_CHAR | NCNAME_START_CHAR | NAME_CHAR | NCNAME_CHAR
};

const char *char_flags_to_string(unsigned int flags)
{
  switch(flags) {
  case 0:
    return "0";

  case NCNAME_START_CHAR:
    return "NCNAME_START_CHAR";
  case NCNAME_CHAR:
    return "NCNAME_CHAR";
  case NAME_START_CHAR:
    return "NAME_START_CHAR";
  case NAME_CHAR:
    return "NAME_CHAR";
  case WHITESPACE_CHAR:
    return "WHITESPACE_CHAR";
  case NON_RESTRICTED_CHAR:
    return "NON_RESTRICTED_CHAR";

  case NON_RESTRICTED_CHAR | WHITESPACE_CHAR:
    return "NON_RESTRICTED_CHAR | WHITESPACE_CHAR";
  case NON_RESTRICTED_CHAR | NAME_CHAR | NCNAME_CHAR:
    return "NON_RESTRICTED_CHAR | NAME_CHAR | NCNAME_CHAR";
  case NON_RESTRICTED_CHAR | NAME_START_CHAR | NAME_CHAR:
    return "NON_RESTRICTED_CHAR | NAME_START_CHAR | NAME_CHAR";
  case NON_RESTRICTED_CHAR | NAME_START_CHAR | NCNAME_START_CHAR | NAME_CHAR | NCNAME_CHAR:
    return "NON_RESTRICTED_CHAR | NAME_START_CHAR | NCNAME_START_CHAR | NAME_CHAR | NCNAME_CHAR";
  }

  return "UNKNOWN";
}

unsigned int char_flags_impl(Char32 c)
{
  unsigned int min, max, middle, result;
  int cmp;

  if(c < 256) return char_flags_256[c];

  // Binary search in the char_classes table
  min = 0;
  max = CHAR_CLASSES_SIZE;

  while(min < max) {
    middle = (max + min) >> 1;

    cmp = char_classes[middle].c - c;
    if(cmp > 0) max = middle;
    else if(cmp < 0) {
      result = middle;
      min = middle + 1;
    }
    else {
      result = middle;
      break;
    }
  }

  return char_classes[result].flags;
}
